### ISSUE TITLE
IBM HTTP Server docker image no longer builds

### ISSUE THREAD

**Issue by aussiecoder-ash** [IBM-i2/analyze-deployment#2]
The IBM HTTP Server docker image is no longer available on dockerhub, this affects the building of IHS docker image [dockerfile](https://github.com/IBM-i2/Analyze-Deployment/blob/master/src/images/common/ihs/Dockerfile)
Alternative methods appear to involve building a docker image using an IHS archive  [fix pack](https://www.ibm.com/support/pages/node/617655)

see example method on github:
[https://github.com/WASdev/ci.docker.ibm-http-server/tree/master/archive](https://github.com/WASdev/ci.docker.ibm-http-server/tree/master/archive)

**Comment by arianahl** [comment]
We are aware and have a fix for it. Will be releasing it soon together with the new version. Thanks!

**Comment by arianahl** [comment]
This has now been fixed in release v2.5.0. Closing.
